name: BetterEconomy
version: '${project.version}'
main: me.hsgamer.bettereconomy.BetterEconomy
api-version: 1.13
softdepend:
  - Vault
  - Treasury
authors:
  - HSGamer
  - takahatashun
description: A simple Vault-based Economy plugin
