name: BetterEconomy
version: '${project.version}'
main: me.hsgamer.bettereconomy.BetterEconomy
api-version: 1.13
depend: [ Vault ]
authors:
  - HSGamer
  - takahatashun
description: A simple Vault-based Economy plugin
