name: BetterEconomy
version: '${project.version}'
main: me.hsgamer.bettereconomy.BetterEconomy
api-version: 1.13
depend: [ Vault ]
authors: [ HSGamer ]
description: A simple Vault-based Economy plugin
